Repository enjin/platform, pull requests merged in 2024-03, with the labels that each got.

#32 Runs platform as www-data user.
  configs/core/Dockerfile
Labels: bug

#35 [PLA-1662] Make decoder image from dockerhub to work on macOS
  docker-compose.yml
Labels: enhancement, Review effort [1-5]: 1

#34 [PLA-1652] Allows www-data to call horizon supervisorctl
  configs/core/Dockerfile
  configs/core/php/memory-limit.ini
  configs/core/routes/web.php
  configs/core/start.sh
  configs/core/supervisor/conf.d/horizon.conf
  configs/core/supervisor/supervisord.conf
  configs/core/supervisor/websockets.conf
  scripts/install-php-redis.sh
  start.bat
  start.sh
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#37 [PLA-1674] Remove daemon submodule use image from dockerhub
  .gitattributes
  .gitmodules
  configs/core/Dockerfile
  docker-compose.yml
  start.bat
  start.sh
Labels: enhancement, Review effort [1-5]: 2, bug_fix
